# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('diffserv', ['core'])
    module.source = [
        'model/filter.cc',
        'model/trafficclass.cc',
        'model/diffserv.cc',
        'helper/diffserv-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('diffserv')
    module_test.source = [
        'test/diffserv-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'diffserv'
    headers.source = [
        'model/filter.h',
        'model/trafficclass.h',
        'model/diffserv.h',
        'helper/diffserv-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

