## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-


def build(bld):
    module = bld.create_ns3_module('json')
    module.source = [
        'jsoncpp.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'json'
    headers.source = [
        'json.h',
        'json-forwards.h',
        ]

    bld.ns3_python_bindings()